/*
 * Copyright (c) 2016. Sascha Lutzenberger. All rights reserved.
 *
 * This file is part of the project "Abload_Tool"
 *
 * Redistribution and use in source and binary forms, without modification,
 * are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * - The author of this source code has given you the permission to use this
 *   source code.
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 * - The code is not used in commercial projects, except you got the permission
 *   for using the code in any commerical projects from the author.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.lutzenberger.sascha.abload.data;

import java.io.Serializable;

import org.apache.http.cookie.ClientCookie;
import org.apache.http.cookie.Cookie;
import org.apache.http.impl.cookie.BasicClientCookie;

/**
 * This is the corresponding Java model of the Login API on http://www.abload.de
 *
 * @author Sascha Lutzenberger
 * @version 1.0 - 29.12.2015
 */
public class LoginResponse implements Serializable {
    //The status code returned by http://www.abload.de
    private String code;
    //The user name from http://www.abload.de
    private String user;
    //The actual session string for http://www.abload.de
    private String session;
    //The cookie containing all the information needed
    private transient Cookie clientCookie;

    /**
     * This method sets the status code returned by the Login API from http://www.abload.de
     *
     * @param code The status code of the API
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method sets the user name returned by the Login API from http://www.abload.de
     *
     * @param user The user name of the API
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method sets the obtained sesstion string by the Login API from http://www.abload.de
     *
     * @param session The current session string
     */
    public void setSession(String session) {
        this.session = session;
    }

    /**
     * This method creates the Cookie which is usually set by the http://www.abload.de server on login.
     *
     * @return The Cookie containing the session String.
     */
    public Cookie getSessionCookie() {
        //If cookie has already been created return the cookie
        if(clientCookie == null) {
            //The domain for the Cookie
            String domain = ".abload.de";
            //The path for the Cookie
            String path = "/";

            //Create a new BasicClientCookie containing the Session String named ablgntan (to match the original cookie)
            BasicClientCookie clientCookie = new BasicClientCookie("ablgntan", this.getSession());
            clientCookie.setDomain(domain);
            clientCookie.setPath(path);

            //Those Attributes have to be set in order to make this look like set by the actual web server
            clientCookie.setAttribute(ClientCookie.PATH_ATTR, path);
            clientCookie.setAttribute(ClientCookie.DOMAIN_ATTR, domain);

            this.clientCookie = clientCookie;
        }

        return clientCookie;
    }

    /**
     * Return the Session of the current connection.
     *
     * @return The session generated by the Login API on http://www.abload.de
     */
    public String getSession() {
        return this.session;
    }
}
