package com.lutzenberger.sascha.abload.data;

import java.io.Serializable;

import org.apache.http.cookie.ClientCookie;
import org.apache.http.cookie.Cookie;
import org.apache.http.impl.cookie.BasicClientCookie;

/**
 * This is the corresponding Java model of the Login API on http://www.abload.de
 *
 * @author Sascha Lutzenberger
 * @version 1.0 - 29.12.2015
 */
public class LoginResponse implements Serializable {
    //The status code returned by http://www.abload.de
    private String code;
    //The user name from http://www.abload.de
    private String user;
    //The actual session string for http://www.abload.de
    private String session;
    //The cookie containing all the information needed
    private Cookie clientCookie;

    /**
     * This method sets the status code returned by the Login API from http://www.abload.de
     *
     * @param code The status code of the API
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method sets the user name returned by the Login API from http://www.abload.de
     *
     * @param user The user name of the API
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method sets the obtained sesstion string by the Login API from http://www.abload.de
     *
     * @param session The current session string
     */
    public void setSession(String session) {
        this.session = session;
    }

    /**
     * This method creates the Cookie which is usually set by the http://www.abload.de server on login.
     *
     * @return The Cookie containing the session String.
     */
    public Cookie getSessionCookie() {
        //If cookie has already been created return the cookie
        if(clientCookie == null) {
            //The domain for the Cookie
            String domain = ".abload.de";
            //The path for the Cookie
            String path = "/";

            //Create a new BasicClientCookie containing the Session String named ablgntan (to match the original cookie)
            BasicClientCookie clientCookie = new BasicClientCookie("ablgntan", this.getSession());
            clientCookie.setDomain(domain);
            clientCookie.setPath(path);

            //Those Attributes have to be set in order to make this look like set by the actual web server
            clientCookie.setAttribute(ClientCookie.PATH_ATTR, path);
            clientCookie.setAttribute(ClientCookie.DOMAIN_ATTR, domain);

            this.clientCookie = clientCookie;
        }

        return clientCookie;
    }

    /**
     * Return the Session of the current connection.
     *
     * @return The session generated by the Login API on http://www.abload.de
     */
    public String getSession() {
        return this.session;
    }
}
